from typing import Any, List, Sequence

def set_seed(seed: int) -> None: ...
def randfloat() -> float: ...
def randint(min: int, max: int) -> int: ...
def uniform(min: float, max: float) -> float: ...
def choice(lst: Sequence[Any]) -> Any: ...
def sample(lst: Sequence[Any], k: int) -> List[Any]: ...
def shuffle(lst: List[Any]) -> None: ...
def randint_array(min: int, max: int, size: int) -> List[int]: ...
def random_array(size: int) -> List[float]: ...
